name: flutter_facebook_auth
description: A plugin that easily adds Facebook authentication into you Flutter app. Feature includes getting user information, profile picture and more. This plugin also supports Web.
version: 4.3.4+2
homepage: https://github.com/darwin-morocho/flutter-facebook-auth

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  # flutter_facebook_auth_platform_interface: ^3.1.2
  # flutter_facebook_auth_platform_interface:
  #   path: ../facebook_auth_platform_interface
  flutter_facebook_auth_platform_interface:
    git:
      url: https://github.com/xbrny/flutter-facebook-auth
      path: facebook_auth_platform_interface
  # flutter_facebook_auth_web: ^3.1.2
  # flutter_facebook_auth_web:
  #   path: ../facebook_auth_web
  flutter_facebook_auth_web:
    git:
      url: https://github.com/xbrny/flutter-facebook-auth
      path: facebook_auth_web

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: app.meedu.flutter_facebook_auth
        pluginClass: FlutterFacebookAuthPlugin
      ios:
        pluginClass: FlutterFacebookAuthPlugin
      web:
        default_package: flutter_facebook_auth_web
