# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.2'
      - name: Install facebook_auth dependencies 
        run: cd facebook_auth && flutter pub get

      - name: Run facebook_auth tests
        run: cd facebook_auth && flutter test --coverage
      
      - name: Install facebook_auth_platform_interface dependencies
        run: cd facebook_auth_platform_interface && flutter pub get

      - name: Run facebook_auth_platform_interface tests
        run: cd facebook_auth_platform_interface && flutter test --coverage

      - name: Install facebook_auth_web dependencies 
        run: cd facebook_auth_web && flutter pub get

      - name: Run facebook_auth_platform_interface tests 
        run: cd facebook_auth_web && flutter test --platform chrome

      - name: Upload coverage to Codecov
        run: curl -s https://codecov.io/bash | bash
